_target_: src.agents.ddpg.init
_convert_: all
state_dim: ${state_dim}
action_dim: ${action_dim}
mlp_dims: [512, 512]
learning_rate: 3e-4
num_iterations: 500
std_schedule: "linear(1.0, 0.1, 50)"
std_clip: 0.3
nstep: 1 # TODO always 1 to make it work with SVGP training?
gamma: 0.99
tau: 0.005
device: ${device}
